/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'bg-blue-50',
    'border-blue-200',
    'text-blue-500',
    'fill-blue-100',
    'bg-amber-50',
    'border-amber-200',
    'text-amber-500',
    'fill-amber-100',
    'bg-green-50',
    'border-green-200',
    'text-green-500',
    'fill-green-100',
    'bg-purple-50',
    'border-purple-200',
    'text-purple-500',
    'fill-purple-100',
    'bg-indigo-50',
    'border-indigo-200',
    'text-indigo-500',
    'fill-indigo-100',
    'bg-cyan-50',
    'border-cyan-200',
    'text-cyan-600',
    'fill-cyan-100',
    'bg-emerald-50',
    'border-emerald-200',
    'text-emerald-600',
    'fill-emerald-100',
    'bg-rose-50',
    'border-rose-200',
    'text-rose-500',
    'fill-rose-100',
  ],
  theme: {
    extend: {
      colors: {
        background: '#FBFBFA',
        card: '#FFFFFF',
        border: '#EBEBEA',
        primary: '#1F1F1E',
        secondary: '#747471',
        text: {
          primary: '#1F1F1E',
          secondary: '#747471',
        },
        accent: {
          DEFAULT: '#EFEFED',
          hover: '#E3E3E0',
        },
      },
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
    },
  },
  plugins: [],
}
